import {
  Loader2,
  X,
  Check,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Search,
  Menu,
  Home,
  User,
  Settings,
  LogOut,
  LogIn,
  Plus,
  Minus,
  Edit,
  Trash,
  Save,
  Download,
  Upload,
  RefreshCw,
  AlertCircle,
  Info,
  HelpCircle,
  Eye,
  EyeOff,
  Copy,
  Clipboard,
  Link,
  ExternalLink,
  Calendar,
  Clock,
  Filter,
  SortAsc,
  SortDesc,
  MoreHorizontal,
  MoreVertical,
  LucideIcon,
  Package,
} from 'lucide-react'

export const Icons = {
  spinner: Loader2,
  close: X,
  check: Check,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  search: Search,
  menu: Menu,
  home: Home,
  user: User,
  settings: Settings,
  logout: LogOut,
  login: LogIn,
  plus: Plus,
  minus: Minus,
  edit: Edit,
  trash: Trash,
  save: Save,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  alert: AlertCircle,
  info: Info,
  help: HelpCircle,
  eye: Eye,
  eyeOff: EyeOff,
  copy: Copy,
  clipboard: Clipboard,
  link: Link,
  external: ExternalLink,
  calendar: Calendar,
  clock: Clock,
  filter: Filter,
  sortAsc: SortAsc,
  sortDesc: SortDesc,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  logo: Package,
}

export type Icon = LucideIcon
